name: Build and Attach Autohotkey Executable to Release

on:
  release:
    types: [created]

jobs:
  build:
    name: Build and Attach Autohotkey Executable to Release
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download and Extract Ahk2Exe Binary File
      run: |
        # Download AutoHotkey zip file.
        Invoke-WebRequest -Uri "https://www.autohotkey.com/download/ahk.zip" -OutFile "ahk.zip"
        # Extract it.
        Expand-Archive -Path "ahk.zip" -DestinationPath "ahk"
        
    - name: Download and Extract Autohotkey v2 Binary File
      run: |
        # Download AutoHotkey zip file.
        Invoke-WebRequest -Uri "https://www.autohotkey.com/download/ahk-v2.zip" -OutFile "ahk-v2.zip"
        # Extract it.
        Expand-Archive -Path "ahk-v2.zip" -DestinationPath "ahk-v2"
        
    - name: Compile Autohotkey Script
      run: |
        # Set the paths to execute more easily.
        $scriptPathIn = "VideoDownloader.ahk"
        $scriptPathOut = "VideoDownloader.exe"
        
        # Compile the script.
        & ahk\Compiler\Ahk2Exe.exe /in $scriptPathIn /out $scriptPathOut /base "ahk-v2\AutoHotkey32.exe" /silent

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Executable
      uses: actions/upload-artifact@v2
      with:
        name: VideoDownloader
        path: VideoDownloader.exe

    - name: Get Artifact URL
      id: get_artifact_url
      run: |
        echo "::set-output name=artifact_url::$(curl -s -X POST -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
        -H 'Accept: application/vnd.github.v3+json' \
        https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts \
        | jq -r '.artifacts[] | select(.name == "VideoDownloader") | .url')"

    - name: Attach Executable to Release
      run: |
        curl -X POST -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
        -H 'Accept: application/vnd.github.v3+json' \
        -H 'Content-Type: application/octet-stream' \
        --data-binary @VideoDownloader.exe "${{ steps.get_artifact_url.outputs.artifact_url }}?name=VideoDownloader.exe"
