name: Build and Attach Autohotkey Executable

on:
  release:
    types: [created]

jobs:
  build:
    name: Build and Attach Autohotkey Executable
    runs-on: windows-latest

    steps:
    - name: Download and Extract AutoHotkey
      run: |
        # Download AutoHotkey zip file.
        Invoke-WebRequest -Uri "https://www.autohotkey.com/download/ahk.zip" -OutFile "ahk.zip"
        # Extract it.
        Expand-Archive -Path "ahk.zip" -DestinationPath "ahk"

    - name: Compile AutoHotkey Script
      run: |
        # Set the paths to execute more easy.
        $scriptPathIn = "VideoDownloader.ahk"
        $scriptPathOut = "VideoDownloader.exe"

        # Compile the script.
        & ahk\Compiler\Ahk2Exe.exe /in $scriptPathIn /out $scriptPathOut /silent

    - name: Upload Executable
      uses: actions/upload-artifact@v2
      with:
        name: VideoDownloader
        path: VideoDownloader.exe
