name: Build and Attach Autohotkey Executable to Release

on:
  release:
    types: [created]

jobs:
  build_and_attach:
    name: Build and Attach Autohotkey Executable to Release

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install AutoHotkey
      run: |
        wget https://www.autohotkey.com/download/ahk.zip
        unzip ahk.zip -d ahk
        chmod +x ahk/AutoHotkeyU64.exe
        echo 'wine ahk/AutoHotkeyU64.exe %*' > ahk/AutoHotkeyU64
        chmod +x ahk/AutoHotkeyU64
        sudo mv ahk/AutoHotkeyU64 /usr/local/bin

    - name: Install Ahk2Exe
      run: |
        wget https://www.autohotkey.com/download/ahk-v2.zip
        unzip ahk-v2.zip -d ahk-v2
        chmod +x ahk-v2/Compiler/Ahk2Exe.exe
        echo 'wine ahk-v2/Compiler/Ahk2Exe.exe $*' > ahk-v2/Compiler/Ahk2Exe
        chmod +x ahk-v2/Compiler/Ahk2Exe
        sudo mv ahk-v2/Compiler/Ahk2Exe /usr/local/bin

    - name: Compile Autohotkey Script
      run: |
        scriptPathIn="VideoDownloader.ahk"
        scriptPathOut="VideoDownloader.exe"
        
        AutoHotkeyU32 $scriptPathIn
        
    - name: Set environment for github-release
      run: |
        echo ::set-env name=RELEASE_TAG::"${{ github.ref }}"
        echo ::set-env name=RELEASE_NAME::"Release ${{ github.ref }}"

    - name: Upload Executable to Release
      uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.RELEASE_TAG }}
        name: ${{ env.RELEASE_NAME }}
        files: "VideoDownloader.exe"

    - name: Cleanup
      run: |
        rm VideoDownloader.exe
