name: Build and Attach Autohotkey Binary File

on:
  release:
    types: [created]

jobs:
  Build-and-Attach:
    name: Start-Building
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ahk2Exe
        uses: nekocodeX/GitHub-Action-Ahk2Exe@main
        with:
          in: VideoDownloader.ahk

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: VideoDownloader.exe
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
