name: Create new GitHub Pre-release and Attach Autohotkey Executable

on:
  push:
    branches:
      - development
    tags:
      - 'v*'
  pull_request:
    branches:
      - development

jobs:
  build:
    name: Build and Upload Executable Artifact
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download and Extract Ahk2Exe Binary File
      run: |
        # Download AutoHotkey zip file.
        Invoke-WebRequest -Uri "https://www.autohotkey.com/download/ahk.zip" -OutFile "ahk.zip"
        # Extract it.
        Expand-Archive -Path "ahk.zip" -DestinationPath "ahk"

    - name: Download and Extract Autohotkey v2 Binary File
      run: |
        # Download AutoHotkey zip file.
        Invoke-WebRequest -Uri "https://www.autohotkey.com/download/ahk-v2.zip" -OutFile "ahk-v2.zip"
        # Extract it.
        Expand-Archive -Path "ahk-v2.zip" -DestinationPath "ahk-v2"

    - name: Compile Autohotkey Script
      run: |
        # Set the paths to execute more easily.
        $scriptPathIn = "VideoDownloader.ahk"
        $scriptPathOut = "VideoDownloader.exe"

        # Compile the script.
        ahk\Compiler\Ahk2Exe.exe /in $scriptPathIn /out $scriptPathOut /base "ahk-v2\AutoHotkey64.exe" /silent

    - name: Upload Executable as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: VideoDownloaderExecutable
        path: VideoDownloader.exe

  create_release:
    name: Download Executable Artifact and Create Pre-release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Download Executable Artifact
      uses: actions/download-artifact@v3
      with:
        name: VideoDownloaderExecutable
        path: VideoDownloader(development-beta).exe

    - name: Rename Executable
      id: "rename_executable_id"
      run: |
        # Set the old and new file names.
        oldFileName="VideoDownloader(development-beta).exe"
        newFileName="VideoDownloader(development-beta ${{ github.run_number }}).exe"

        # Rename the file.
        mv "$oldFileName" "$newFileName"

        # Export the new file name to be used in the next step.
        echo "::set-output name=newFileName::$newFileName"

    - name: Upload Renamed Executable as Artifact for Release
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.rename_executable_id.outputs.newFileName }}
        path: ${{ steps.rename_executable_id.outputs.newFileName }}

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ steps.rename_executable_id.outputs.newFileName }}
        artifactContentType: application/executable
        body: "This is the latest beta pre release. May be changed in the future."
        generateReleaseNotes: true
        makeLatest: false
        prerelease: true
        removeArtifacts: true
        name: "latest-development-beta-pre-release ${{ github.run_number }}"
        tag: "latest-development-beta"