name: Build and Attach Autohotkey Executable to Release

on:
  release:
    types: [created]

jobs:
  build_and_attach:
    name: Build and Attach Autohotkey Executable to Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download and Install Autohotkey v2 for Linux
      run: |
        # Install dependencies required for running AutoHotkey v2 on Linux
        sudo apt-get update
        sudo apt-get install -y libc6-dev libx11-dev
        
        # Download AutoHotkey v2 binary for Linux
        wget "https://www.autohotkey.com/download/ahk-v2.zip"
        unzip ahk-v2.zip
        chmod +x ahk-v2/Compiler/Ahk2Exe
        
    - name: Compile Autohotkey Script
      run: |
        # Set the paths to execute more easily.
        scriptPathIn="VideoDownloader.ahk"
        scriptPathOut="VideoDownloader.exe"
        
        # Compile the script using AutoHotkey v2
        ./ahk-v2/Compiler/Ahk2Exe /in "$scriptPathIn" /out "$scriptPathOut" /silent

    - name: Set environment for github-release
      run: |
        echo ::set-env name=RELEASE_TAG::"${{ github.ref }}"
        echo ::set-env name=RELEASE_NAME::"Release ${{ github.ref }}"

    - name: Upload Executable to Release
      uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.RELEASE_TAG }}
        name: ${{ env.RELEASE_NAME }}
        files: "VideoDownloader.exe"

    - name: Cleanup
      run: |
        rm VideoDownloader.exe
