name: Create new GitHub Pre-release and Attach Autohotkey Executable

on:
  push:
    branches:
      - development
    tags:
      - 'v*'
  pull_request:
    branches:
      - development

jobs:
  build:
    name: Build and Upload Executable Artifact
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download and Extract Ahk2Exe Binary File
      run: |
        # Set variables
        $ahkZipURL = "https://www.autohotkey.com/download/ahk.zip"
        $ahkV2ZipURL = "https://www.autohotkey.com/download/ahk-v2.zip"
        $ahkFolder = "ahk"
        $ahkV2Folder = "ahk-v2"

        # Download AutoHotkey zip files.
        Invoke-WebRequest -Uri $ahkZipURL -OutFile "ahk.zip"
        Invoke-WebRequest -Uri $ahkV2ZipURL -OutFile "ahk-v2.zip"

        # Extract the files.
        Expand-Archive -Path "ahk.zip" -DestinationPath $ahkFolder
        Expand-Archive -Path "ahk-v2.zip" -DestinationPath $ahkV2Folder

    - name: Compile Autohotkey Script
      run: |
        # Set the paths to execute more easily.
        $scriptPathIn = "VideoDownloader.ahk"
        $scriptPathOut = "VideoDownloader(development-beta).exe"

        # Compile the script.
        ahk\Compiler\Ahk2Exe.exe /in $scriptPathIn /out $scriptPathOut /base "$env:GITHUB_WORKSPACE\$ahkV2Folder\AutoHotkey64.exe" /silent

    - name: Upload Executable as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: VideoDownloader(development-beta).exe"
        path: VideoDownloader(development-beta).exe"

  create_release:
    name: Download Executable Artifact and Create Pre-release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Download Executable Artifact
      uses: actions/download-artifact@v3
      with:
        name: VideoDownloader(development-beta).exe"

    - name: Upload Executable as Artifact for Release
      uses: actions/upload-artifact@v2
      with:
        name: VideoDownloader(development-beta).exe"
        path: VideoDownloader(development-beta).exe"

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "VideoDownloader.exe"
        artifactContentType: application/gzip
        body: "This is the latest beta pre release. May be changed in the future."
        generateReleaseNotes: true
        makeLatest: false
        prerelease: true
        removeArtifacts: true
        name: "latest-development-beta-pre-release ${{ github.run_number }}"
        tag: "latest-development-beta"