name: Build and Attach Autohotkey Executable to Release

on:
  release:
    types: [created]

jobs:
  build_and_attach:
    name: Build and Attach Autohotkey Executable to Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Wine
      run: sudo apt-get update && sudo apt-get install -y wine

    - name: Download and Extract Ahk2Exe Binary File
      run: |
        # Download AutoHotkey zip file.
        wget "https://www.autohotkey.com/download/ahk.zip"
        # Extract it.
        unzip ahk.zip -d ahk
        
    - name: Download and Extract Autohotkey v2 Binary File
      run: |
        # Download AutoHotkey zip file.
        wget "https://www.autohotkey.com/download/ahk-v2.zip"
        # Extract it.
        unzip ahk-v2.zip -d ahk-v2
        
    - name: Compile Autohotkey Script
      run: |
        # Set the paths to execute more easily.
        scriptPathIn="VideoDownloader.ahk"
        scriptPathOut="VideoDownloader.exe"
        
        # Compile the script using AutoHotkey v2 through Wine
        wine ahk/Compiler/Ahk2Exe.exe /in "$scriptPathIn" /out "$scriptPathOut" /base "ahk-v2/AutoHotkey32.exe" /silent

    - name: Set environment for github-release
      run: |
        echo ::set-env name=RELEASE_TAG::"${{ github.ref }}"
        echo ::set-env name=RELEASE_NAME::"Release ${{ github.ref }}"

    - name: Upload Executable to Release
      uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.RELEASE_TAG }}
        name: ${{ env.RELEASE_NAME }}
        files: "VideoDownloader.exe"

    - name: Cleanup
      run: |
        rm VideoDownloader.exe
